travis:
  secure:
    BINSTAR_TOKEN: IFUTtF/c2k9fsXDJNWWVyidbI+zgoq0893EpEYITiYKpdVrCtl7yw16vRjSiiG1i00dRk5cc6MLceq6Z5AtEF+V3Hq+F5JjsVggQAO43hmKf20Czr6DB5E4VWjcK6mupQVPOnDMlsaoJGXOQH6WAeFypD5PmKoa0r+I2rxEnJL6eijrlSPXAO79t1PcvF9I0fuWOK1aCSS+EepH9Jz5LIRgHn9X+JKQNkTWceqDcUY2fue5g20jv7wg1rWRuVJqfZbnXCrDiijR6nmmI/tAmfAb1ssTnML3nlnau/Pv/0Jrs+GYXrvAVvVS3drzrfnhwJoXi2lwciP4y/D2Az8WX/kAEurD16rWfgBD4fm4P7llpex320be/SLsNj4TgBXXPOnI8yzgWjaSno//hzvwqGA4XMQm1jAqYNPZnbtgKcPWLCOQY/llUsrAE/xOhd/hYamg9ppF8xI1B6yJoAPecwvfnOWVnxP4CKq9AvKyfItkJ0ibCLWCJSg8WxneuLt9XvZAlGnfYJzjcHx4mJ6w9ynVc+8lzaXFWng0pfCFfcOU2lD9cRiEZIChAgOaangzxcZ6T2H+FSkojghS2X7yVJRahEMQlF8QVRhF1Ut3JywSeOa2cp0zzG1nd34hPYUPT5Uh5us+SW0FZ4ftrciakdI3pIs13esFRQ3GZ9ZoXm5A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
