travis:
  secure:
    BINSTAR_TOKEN: xcyowiDw5VNwi47JaTL2dUke8l+o49WiK61sTvPtIEaDgyAO9Q7hLzCLm2MIwMFLn35vTtc/KOr3VkTU4f1Vye5yvVd4Vf2i8YHapwwEoZwCq55PHkxhlaHdYn/3chDU7NQzoSaLNPuDQT4e0WetZgP4Fr10YBXpSH07cZdFXfRQrFYNGF4hb7KDvNsRDxmsH009gdeShUiplJmZn6dqZn8QXlxS2fYHj1pptVbpRur7FGnr+Gv+GxU+TrW8IrMgaxAIAu0xM2DaOxA5wMIQWrXRFSI4fmILl7IJCrCAQm+zEDO1hTTwxJM2RtmPdGoksJ3NOQvi0/vtbjVUXmWMfXeSWG17jPp7zmD1xGHzYL7isJWAl/8QZX4sonreBpN+1jeK6EYRfnxC/QI3vGkTE2ude67jzJWZMp6pt/o+SDq4TbZknfUI6+0ReSqXQePLUX0rovU/1EvKl62oKmjvrlK6zFo+kEop1vvTuZeufDc6knCh3IBobSZTn2bhGq8WOKaYqIXZ6f89If8al1VfyRLi4q4s7HPgg/oa8z3+APE1yNsxTcempwmffHTheOSKYIW87XTQ4fhjatITcGypJZ4QFeOnAEZ8p7e/OrF20Hbzv+vImajaUAL6HeLWdX3t+isP/1HHx4r9gCic+rAq0xWoh4QGaLLZbmOs88QuWtY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
